### ISSUE TITLE
build function error

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [hughlv/agentok#100]
An error occurred while using build function：

<img width="1669" alt="image" src="https://github.com/hughlv/agentok/assets/144103401/c63e223e-97b2-4494-8c60-23267aee412d">

**Comment by hughlv** [comment]
this is fixed. recently we upgraded some deps, which introduced a few compatibility issues. please let us know if there are any other issues.

**Comment by shanmu-raoyunfei** [comment]
I'm using macos, with the latest code bundle, and it doesn't work. Including the online demo on the official website, it is the same mistake. What can I do to avoid these compatibility issues

**Comment by shanmu-raoyunfei** [comment]
Just found the website working.
